baseURL = "https://jwhiteford.github.io/BattleRiver/"
languageCode = "en-us"
title = "Battle River Overhead Doors"

theme ="navigator-hugo-master"

summaryLength = 10

# Build robots.txt file
enableRobotsTXT = false
# google analytics tracking id
googleAnalytics = "" # your analitics ID

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
logo = "images/Battle-River-Overhead-Doors-logo.svg"

# Gestion des langues : FR / EN / NL / DE
# [[Params.listeLangues]]
# code = "fr"
[[Params.listeLangues]]
code = "en"

# meta data
author = ""
description = ""

# Gestion des langues : FR / EN / NL / DE
[Languages]
[Languages.en]
weight = 1
languageCode = "en-us"
dateFormat = "January 2, 2006"
logo = "images/Battle-River-Overhead-Doors-logo.svg"
menufixed = true

footerDescription = "We're a family run business that's been operating for X years. We proudly serve Camrose, Wetaskiwin, Battle River and Beyond."
# footerServiceTitle = "Service"
# footerQuicklinkTitle = "Quicklinks"
footerAboutTitle = "About"
footerSubscribeTitle = "Subscribe"


# cookies
[params.cookies]
enable = true
expire_days = 14

# Hero Area Section
[Languages.en.params.hero]
enable  = true
heading = "Overhead Doors are our business."
description = "We specialize in installation and service of commercial and residential overhead doors."
button  = true
btnText = "Get in touch"
btnURL  = "/contact"
videoThumb = "images/slider/video-player-thumb.jpg"
videoURL   = "https://www.youtube.com/embed/87ht5wtn8u4"

# About 2 Section
[Languages.en.params.aboutSm]
enable  = true
title   = "We have X years of experience and a passion for quality work"
description = "Possibly write a bit of content about the company and services so the visitor gets a quick rundown of the company to make them feel like they know you and you're safe to hire. A couple sentences is fine, don't want to overwhelm the visitors."

# Blog Section On Homepage
[Languages.en.params.blog]
enable  = true
topTitle= "OUR UNTOLD STORY"
title   = "All about Overhead Doors"
subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

# Contact Section
[Languages.en.params.contact]
enable  = true
topTitle= "SEND US A MESSAGE"
title   = "Contact Us."
subtitle= "We're happy to hear from you! Call us to chat or send us an email if you're feeling shy."
address = " RR # 1 Edberg AB, Canada"
phone   = "780-608-9790"
# fax     = "+61 3827 3590"
facebook= "https://www.facebook.com/"
# twitter = "https://twitter.com/"
# linkedin= "https://www.linkedin.com/"
# dribbble= "https://dribbble.com/"
# instagram= "https://www.instagram.com/"
# mapLatitude = "51.507351"
mapLongitude= "-0.127758"
mapMarker   = "images/marker.png"

# Call to Action Section on About Page
[Languages.en.params.cta]
enable  = true
bg      = "images/call-to-action/call-to-action-bg-2.jpg"
title   = "Let's Create Something Together"
subtitle= "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
btnText = "Contact Us"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
# Navbar Menus
# [[menu.nav]]
# name    = "about"
# url     = "about"
# weight  = 2
[[menu.nav]]
name    = "service"
url     = "service"
weight  = 1
[[menu.nav]]
name    = "gallery"
url     = "portfolio"
weight  = 2
[[menu.nav]]
name    = "contact"
url     = "contact"
weight  = 3
# [[menu.nav]]
# name    = "blog"
# url     = "blog"
# weight  = 5

# Footer Service Menu
[[menu.service]]
name    = "graphicdesign"
url     = "service"
weight  = 1
[[menu.service]]
name    = "webdesign"
url     = "service"
weight  = 2
[[menu.service]]
name    = "webdevelopment"
url     = "service"
weight  = 3

# Footer Quick links Menu
# [[menu.quicklink]]
# name    = "partners"
# url     = "about"
# weight  = 1
# [[menu.quicklink]]
# name    = "about"
# url     = "about"
# weight  = 2
# [[menu.quicklink]]
# name    = "faqs"
# url     = "about"
# weight  = 3
# [[menu.quicklink]]
# name    = "badges"
# url     = "about"
# weight  = 4
